# Generated by Django 4.0.1 on 2022-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('announcment', models.CharField(max_length=250, verbose_name='Announcment')),
                ('full_text', models.TextField(verbose_name='An acrticle')),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
